import type { ConsumerCard, Material, NormalizedSolveInput, SourceRef } from '@/lib/consumer-safety/types'
import { containsUnnegatedTerm } from '@/lib/consumer-safety/helpers'

const source = (...labels: string[]): SourceRef[] => labels.map((label) => ({ kind: 'reference', label }))

const PHASE0_EVIDENCE = {
  proteinHeat: source('phase0-evidence-001'),
  proteinPolyester: source('phase0-evidence-002'),
  tanninAlkali: source('phase0-evidence-003'),
  tannin: source('phase0-evidence-004'),
  tanninCotton: source('phase0-evidence-005'),
  cottonOilHold: source('phase0-evidence-006'),
  cottonBoundary: source('phase0-evidence-007'),
  denimBoundary: source('phase0-evidence-008'),
  proteinCotton: source('phase0-evidence-009'),
  proteinTannin: source('phase0-evidence-010'),
  leatherBoundary: source('phase0-evidence-011'),
  suedeBoundary: source('phase0-evidence-012'),
  silkBoundary: source('phase0-evidence-013'),
  woolBoundary: source('phase0-evidence-014'),
  dyeInk: source('phase0-evidence-015'),
  acidFiber: source('phase0-evidence-016'),
}

export const CONSUMER_CARDS_PHASE0: ConsumerCard[] = [
  {
    id: 'consumer-blood-cotton-fresh',
    stainType: 'protein',
    materials: ['cotton'],
    title: 'Fresh Blood on Washable Cotton',
    safeSteps: ['Blot only; do not rub.', 'Rinse with cold water from the back when possible.', 'Use a small amount of mild detergent only if the label says washable.', 'Air dry and inspect before any heat.'],
    avoid: ['No warm or hot water.', 'No dryer.', 'No bleach unless separately reviewed for white cotton.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinHeat,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
  },
  {
    id: 'consumer-blood-polyester-fresh',
    stainType: 'protein',
    materials: ['polyester'],
    title: 'Fresh Blood on Washable Polyester',
    safeSteps: ['Blot only; do not rub.', 'Rinse with cold water.', 'Use mild detergent if washable and colorfast.', 'Air dry and inspect before heat.'],
    avoid: ['No hot water.', 'No dryer.', 'No repeated scrubbing.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinPolyester,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
  },
  {
    id: 'consumer-coffee-cotton-black',
    stainType: 'tannin',
    materials: ['cotton'],
    title: 'Black Coffee on Washable Cotton',
    safeSteps: ['Blot liquid with a clean white cloth.', 'Flush with cool water if washable.', 'Use mild detergent only after colorfastness is known.', 'Air dry and inspect before heat.'],
    avoid: ['No ammonia or baking soda.', 'No chlorine bleach on colored cotton.', 'No dryer until clear.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.tanninAlkali,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
  },
  {
    id: 'consumer-tea-cotton',
    stainType: 'tannin',
    materials: ['cotton'],
    title: 'Tea on Washable Cotton',
    safeSteps: ['Blot the spill.', 'Flush with cool water if the label allows washing.', 'Use mild detergent if colorfast.', 'Air dry and inspect.'],
    avoid: ['No ammonia or baking soda.', 'No heat until clear.', 'No bleach on colored fabric.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.tannin,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
  },
  {
    id: 'consumer-red-wine-cotton',
    stainType: 'tannin',
    materials: ['cotton'],
    title: 'Red Wine on Washable Cotton',
    safeSteps: ['Blot up liquid immediately.', 'Flush with cool water if washable.', 'Use mild detergent if colorfast.', 'Air dry; refer if color remains.'],
    avoid: ['No rubbing.', 'No ammonia or baking soda.', 'No dryer heat.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.tanninAlkali,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: true,
  },
  {
    id: 'consumer-juice-cotton',
    stainType: 'tannin',
    materials: ['cotton'],
    title: 'Fruit Juice on Washable Cotton',
    safeSteps: ['Blot liquid.', 'Flush with cool water if washable.', 'Use mild detergent if colorfast.', 'Air dry and inspect.'],
    avoid: ['No heat.', 'No alkaline cleaners.', 'No bleach on colored cotton.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.tannin,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: true,
  },
  {
    id: 'consumer-tomato-cotton',
    stainType: 'tannin',
    materials: ['cotton'],
    title: 'Tomato Sauce on Washable Cotton',
    safeSteps: ['Lift off solids gently.', 'Blot; do not rub.', 'Flush with cool water if washable.', 'Use mild detergent only if colorfast, then air dry.'],
    avoid: ['No heat.', 'No ammonia or baking soda.', 'No bleach on colored fabric.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.tanninCotton,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: true,
  },
  {
    id: 'consumer-cooking-oil-cotton',
    stainType: 'oil_grease',
    materials: ['cotton'],
    title: 'Cooking Oil on Washable Cotton',
    safeSteps: ['Blot excess oil.', 'Cover with absorbent powder if available; let it sit, then lift away.', 'Use mild detergent if washable and colorfast.', 'Air dry and inspect before heat.'],
    avoid: ['Do not rub oil deeper.', 'No dryer until clear.', 'No solvents at home.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.cottonOilHold,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: true,
  },
  {
    id: 'consumer-butter-cotton',
    stainType: 'oil_grease',
    materials: ['cotton'],
    title: 'Butter on Washable Cotton',
    safeSteps: ['Lift excess butter gently.', 'Blot oil residue.', 'Use mild detergent if washable and colorfast.', 'Air dry and inspect before heat.'],
    avoid: ['No hot dryer.', 'No solvents.', 'No rubbing.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.cottonBoundary,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: true,
  },
  {
    id: 'consumer-mud-denim',
    stainType: 'particulate',
    materials: ['denim'],
    title: 'Mud on Washable Denim',
    safeSteps: ['Let wet mud dry first.', 'Brush away loose soil gently.', 'Rinse with cool water if washable.', 'Use mild detergent and air dry.'],
    avoid: ['Do not smear wet mud.', 'No bleach on denim.', 'No high heat until clear.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.denimBoundary,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: true,
  },
  {
    id: 'consumer-sweat-white-cotton',
    stainType: 'protein',
    materials: ['cotton'],
    title: 'Sweat on Washable White Cotton',
    safeSteps: ['Keep the area cool.', 'Rinse with cool water if washable.', 'Use mild detergent.', 'Air dry and inspect before heat.'],
    avoid: ['No dryer until clear.', 'No chlorine bleach unless separately reviewed.', 'No ammonia.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinCotton,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: true,
  },
  {
    id: 'consumer-chocolate-cotton',
    stainType: 'mixed_unknown',
    materials: ['cotton'],
    title: 'Chocolate on Washable Cotton',
    safeSteps: ['Lift excess gently.', 'Use cold water first because chocolate can include protein.', 'Use mild detergent if washable and colorfast.', 'Air dry and inspect.'],
    avoid: ['No hot water.', 'No dryer until clear.', 'No bleach on colored fabric.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinCotton,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: true,
  },
  {
    id: 'consumer-coffee-with-cream-cotton',
    stainType: 'mixed_unknown',
    materials: ['cotton'],
    title: 'Coffee With Cream on Washable Cotton',
    safeSteps: ['Blot liquid.', 'Use cool water first because cream adds protein.', 'Use mild detergent if washable and colorfast.', 'Air dry and inspect.'],
    avoid: ['No hot water.', 'No ammonia or baking soda.', 'No dryer until clear.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinTannin,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: true,
  },
  {
    id: 'consumer-urine-cotton',
    stainType: 'protein',
    materials: ['cotton'],
    title: 'Urine on Washable Cotton',
    safeSteps: ['Blot moisture.', 'Rinse with cool water if washable.', 'Use mild detergent.', 'Air dry and refer if odor remains.'],
    avoid: ['No heat.', 'No bleach/ammonia mixing.', 'Do not mask odor with fragrance.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinHeat,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: true,
  },
  {
    id: 'consumer-leather-any-stain',
    stainType: 'mixed_unknown',
    materials: ['leather'],
    title: 'Any Stain on Leather',
    safeSteps: [],
    avoid: ['Do not use water, dish soap, alcohol, acetone, bleach, or heat.', 'Do not rub.', 'Do not keep experimenting.'],
    maxVerdict: 'stop_use_pro',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.leatherBoundary,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
  },
  {
    id: 'consumer-suede-any-stain',
    stainType: 'mixed_unknown',
    materials: ['suede'],
    title: 'Any Stain on Suede or Nubuck',
    safeSteps: [],
    avoid: ['Do not wet suede.', 'Do not use soap, alcohol, solvents, oil cleaners, or bleach.', 'Do not rub the nap.'],
    maxVerdict: 'stop_use_pro',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.suedeBoundary,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
  },
  {
    id: 'consumer-silk-any-protein-dye',
    stainType: 'mixed_unknown',
    materials: ['silk'],
    title: 'Protein, Dye, or Unknown Stain on Silk',
    safeSteps: [],
    avoid: ['Do not use enzyme detergent, bleach, peroxide, hot water, or acetone.', 'Do not rub or wring.', 'Do not machine wash.'],
    maxVerdict: 'stop_use_pro',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.silkBoundary,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
  },
  {
    id: 'consumer-wool-any-protein-dye',
    stainType: 'mixed_unknown',
    materials: ['wool'],
    title: 'Protein, Dye, or Unknown Stain on Wool',
    safeSteps: [],
    avoid: ['Do not use enzyme detergent, chlorine bleach, hot water, or agitation.', 'Do not wring.', 'Do not machine dry.'],
    maxVerdict: 'stop_use_pro',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.woolBoundary,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
  },
  {
    id: 'consumer-dye-transfer-any',
    stainType: 'dye',
    materials: ['cotton', 'linen', 'denim', 'polyester', 'nylon', 'wool', 'silk', 'rayon_viscose', 'acetate', 'leather', 'suede', 'blend', 'unknown'],
    title: 'Dye Transfer or Color Bleed',
    safeSteps: [],
    avoid: ['Do not rub.', 'Do not bleach.', 'Do not use alcohol, acetone, or peroxide at home.'],
    maxVerdict: 'stop_use_pro',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.dyeInk,
    sourceSupport: 'yes',
    proChemistryInSource: true,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
  },
  {
    id: 'consumer-rust-any',
    stainType: 'rust_mineral',
    materials: ['cotton', 'linen', 'denim', 'polyester', 'nylon', 'wool', 'silk', 'rayon_viscose', 'acetate', 'blend', 'unknown'],
    title: 'Rust or Mineral Stain',
    safeSteps: [],
    avoid: ['Do not use chlorine bleach.', 'Do not use strong acids.', 'Do not heat.'],
    maxVerdict: 'stop_use_pro',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.acidFiber,
    sourceSupport: 'partial',
    proChemistryInSource: true,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
]

const ANY_STOP_MATERIALS = new Set<Material>(['silk', 'wool', 'leather', 'suede'])

const CARD_MATCH_TERMS: Record<string, string[]> = {
  'consumer-blood-cotton-fresh': ['blood'],
  'consumer-blood-polyester-fresh': ['blood'],
  'consumer-coffee-cotton-black': ['coffee', 'black coffee'],
  'consumer-tea-cotton': ['tea'],
  'consumer-red-wine-cotton': ['red wine', 'wine'],
  'consumer-juice-cotton': ['juice', 'fruit juice'],
  'consumer-tomato-cotton': ['tomato', 'tomato sauce'],
  'consumer-cooking-oil-cotton': ['cooking oil', 'vegetable oil', 'olive oil', 'canola oil', 'frying oil', 'food oil', 'kitchen grease', 'bacon grease'],
  'consumer-butter-cotton': ['butter'],
  'consumer-mud-denim': ['mud', 'soil', 'dirt'],
  'consumer-sweat-white-cotton': ['sweat', 'perspiration'],
  'consumer-chocolate-cotton': ['chocolate'],
  'consumer-coffee-with-cream-cotton': ['coffee with cream', 'cream in coffee', 'coffee and cream'],
  'consumer-urine-cotton': ['urine', 'pee'],
  'consumer-dye-transfer-any': ['dye transfer', 'color bleed', 'colour bleed', 'ink', 'marker', 'hair dye'],
  'consumer-rust-any': ['rust', 'iron stain', 'mineral'],
}

function cardSpecificityScore(card: ConsumerCard, input: NormalizedSolveInput): number {
  return (CARD_MATCH_TERMS[card.id] ?? []).reduce((score, term) => (containsUnnegatedTerm(input.stainDescription, term) ? score + 1 : score), 0)
}

export function findConsumerCard(input: NormalizedSolveInput): ConsumerCard | null {
  const exactCandidates = CONSUMER_CARDS_PHASE0.filter((card) => card.stainType === input.stainType && card.materials.includes(input.material))
  if (exactCandidates.length > 0) {
    const ranked = exactCandidates
      .map((card) => ({ card, score: cardSpecificityScore(card, input) }))
      .sort((a, b) => b.score - a.score)
    if (ranked[0].score > 0) return ranked[0].card
  }

  if (ANY_STOP_MATERIALS.has(input.material)) {
    return (
      CONSUMER_CARDS_PHASE0.find((card) => card.materials.length === 1 && card.materials[0] === input.material && card.safeSteps.length === 0) ??
      null
    )
  }

  if (input.stainType === 'dye' || input.stainType === 'ink') {
    return CONSUMER_CARDS_PHASE0.find((card) => card.id === 'consumer-dye-transfer-any') ?? null
  }

  if (input.stainType === 'rust_mineral') {
    return CONSUMER_CARDS_PHASE0.find((card) => card.id === 'consumer-rust-any' && card.materials.includes(input.material)) ?? null
  }

  return null
}
