import type { ConsumerCard, Material, NormalizedSolveInput, SourceRef } from '@/lib/consumer-safety/types'
import { containsUnnegatedTerm } from '@/lib/consumer-safety/helpers'

const source = (...labels: string[]): SourceRef[] => labels.map((label) => ({ kind: 'reference', label }))

const PHASE0_EVIDENCE = {
  proteinHeat: source('phase0-evidence-001'),
  proteinPolyester: source('phase0-evidence-002'),
  tanninAlkali: source('phase0-evidence-003'),
  tannin: source('phase0-evidence-004'),
  tanninCotton: source('phase0-evidence-005'),
  cottonOilHold: source('phase0-evidence-006'),
  cottonBoundary: source('phase0-evidence-007'),
  denimBoundary: source('phase0-evidence-008'),
  proteinCotton: source('phase0-evidence-009'),
  proteinTannin: source('phase0-evidence-010'),
  leatherBoundary: source('phase0-evidence-011'),
  suedeBoundary: source('phase0-evidence-012'),
  silkBoundary: source('phase0-evidence-013'),
  woolBoundary: source('phase0-evidence-014'),
  dyeInk: source('phase0-evidence-015'),
  acidFiber: source('phase0-evidence-016'),
}

export const CONSUMER_CARDS_PHASE0: ConsumerCard[] = [
  {
    id: 'consumer-blood-cotton-fresh',
    stainType: 'protein',
    materials: ['cotton'],
    title: 'Fresh Blood on Washable Cotton',
    safeSteps: ['Blot only; do not rub.', 'Rinse with cold water from the back when possible.', 'Use a small amount of mild detergent only if the label says washable.', 'Air dry and inspect before any heat.'],
    avoid: ['No warm or hot water.', 'No dryer.', 'No bleach unless separately reviewed for white cotton.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinHeat,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
  },
  {
    id: 'consumer-blood-polyester-fresh',
    stainType: 'protein',
    materials: ['polyester'],
    title: 'Fresh Blood on Washable Polyester',
    safeSteps: ['Blot only; do not rub.', 'Rinse with cold water.', 'Use mild detergent if washable and colorfast.', 'Air dry and inspect before heat.'],
    avoid: ['No hot water.', 'No dryer.', 'No repeated scrubbing.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinPolyester,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
  },
  {
    id: 'consumer-coffee-cotton-black',
    stainType: 'tannin',
    materials: ['cotton'],
    title: 'Black Coffee on Washable Cotton',
    protocolName: 'Cool-water tannin flush with mild detergent finish',
    mechanism:
      'Coffee is a tannin-rich, water-based stain. Cool water dilution moves tannin out of washable cotton before heat can set it; mild detergent helps release residue without jumping to harsher chemistry.',
    sourceFit:
      'Fits Phase 0 only when the item is washable cotton, colorfast or white, not heat-set, and not already treated with alkali, bleach, peroxide, solvents, or other strong products.',
    safeSteps: [
      'Blot liquid with a clean white cloth; do not rub.',
      'If the care label allows washing, flush cool water from the back of the stain.',
      'Work a small amount of mild liquid detergent into the spot with light fingertip pressure.',
      'Rinse cool, then air dry and inspect before any heat.',
    ],
    avoid: ['No ammonia, baking soda, or alkaline cleaners.', 'No chlorine bleach in this first-step protocol.', 'No dryer or iron until the stain is gone.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.tanninAlkali,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
  },
  {
    id: 'consumer-tea-cotton',
    stainType: 'tannin',
    materials: ['cotton'],
    title: 'Tea on Washable Cotton',
    safeSteps: ['Blot the spill.', 'Flush with cool water if the label allows washing.', 'Use mild detergent if colorfast.', 'Air dry and inspect.'],
    avoid: ['No ammonia or baking soda.', 'No heat until clear.', 'No bleach on colored fabric.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.tannin,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
  },
  {
    id: 'consumer-red-wine-cotton',
    stainType: 'tannin',
    materials: ['cotton'],
    title: 'Red Wine on Washable Cotton',
    safeSteps: ['Blot up liquid immediately.', 'Flush with cool water if washable.', 'Use mild detergent if colorfast.', 'Air dry; refer if color remains.'],
    avoid: ['No rubbing.', 'No ammonia or baking soda.', 'No dryer heat.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.tanninAlkali,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-juice-cotton',
    stainType: 'tannin',
    materials: ['cotton'],
    title: 'Fruit Juice on Washable Cotton',
    safeSteps: ['Blot liquid.', 'Flush with cool water if washable.', 'Use mild detergent if colorfast.', 'Air dry and inspect.'],
    avoid: ['No heat.', 'No alkaline cleaners.', 'No bleach on colored cotton.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.tannin,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-tomato-cotton',
    stainType: 'tannin',
    materials: ['cotton'],
    title: 'Tomato Sauce on Washable Cotton',
    safeSteps: ['Lift off solids gently.', 'Blot; do not rub.', 'Flush with cool water if washable.', 'Use mild detergent only if colorfast, then air dry.'],
    avoid: ['No heat.', 'No ammonia or baking soda.', 'No bleach on colored fabric.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.tanninCotton,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-cooking-oil-cotton',
    stainType: 'oil_grease',
    materials: ['cotton'],
    title: 'Cooking Oil on Washable Cotton',
    safeSteps: ['Blot excess oil.', 'Cover with absorbent powder if available; let it sit, then lift away.', 'Use mild detergent if washable and colorfast.', 'Air dry and inspect before heat.'],
    avoid: ['Do not rub oil deeper.', 'No dryer until clear.', 'No solvents at home.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.cottonOilHold,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-butter-cotton',
    stainType: 'oil_grease',
    materials: ['cotton'],
    title: 'Butter on Washable Cotton',
    safeSteps: ['Lift excess butter gently.', 'Blot oil residue.', 'Use mild detergent if washable and colorfast.', 'Air dry and inspect before heat.'],
    avoid: ['No hot dryer.', 'No solvents.', 'No rubbing.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.cottonBoundary,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-grass-denim',
    stainType: 'mixed_unknown',
    materials: ['denim'],
    title: 'Grass Stain on Denim',
    protocolName: 'Cold protein release, chlorophyll transfer, then air-dry inspection',
    mechanism:
      'Grass is not just green dirt. It is chlorophyll pigment bound with plant protein. Denim adds indigo dye risk, so the plan must lift residue without heat, bleach, or heavy rubbing that can leave a pale ring.',
    sourceFit:
      'Fits washable, finished denim when the item is not raw or selvage denim, has not been hot-dried, and the user can hidden-test before any alcohol or oxygen-cleaner step.',
    knowledgeBullets: [
      'Cold water protects the protein side of grass from setting.',
      'Mild dish soap releases the plant protein and surface soil without stripping indigo.',
      'Alcohol can pull chlorophyll, but only after a hidden-seam test on dark or raw denim.',
      'Air drying is part of the treatment: dryer heat can make remaining green permanent.',
    ],
    productGuidance: [
      {
        name: 'Mild liquid dish soap',
        use: 'Use one drop diluted in cool water on a white cloth.',
        note: 'This is the first product because it handles the protein/soil side without jumping to bleach.',
      },
      {
        name: '70% isopropyl alcohol',
        use: 'Use only on a white cloth after a hidden-seam dye test passes.',
        note: 'Do not pour it on denim. Skip on raw, selvage, black-overdyed, or bleeding denim.',
      },
      {
        name: 'Oxygen cleaner',
        use: 'Optional cool-water finish only after the dye test and care label support washing.',
        note: 'Never substitute chlorine bleach on denim.',
      },
    ],
    safeSteps: [
      'Lift loose grass or dirt with a dull spoon; do not rub the denim.',
      'Flush from the back with cold water only, keeping the wet area controlled.',
      'Dab with one drop of mild dish soap diluted in cool water on a clean white cloth.',
      'Hidden-test isopropyl alcohol on an inside seam; if no blue transfers, tamp the green area with alcohol on a cloth, outside-in.',
      'Rinse cool, air-dry fully, and inspect in daylight before any dryer heat.',
    ],
    avoid: [
      'No hot water or dryer heat until the stain is gone.',
      'No chlorine bleach on denim.',
      'Do not rub or scrub the spot.',
      'Do not use alcohol if the hidden-seam test transfers blue dye.',
    ],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.denimBoundary,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-mud-denim',
    stainType: 'particulate',
    materials: ['denim'],
    title: 'Mud on Washable Denim',
    safeSteps: ['Let wet mud dry first.', 'Brush away loose soil gently.', 'Rinse with cool water if washable.', 'Use mild detergent and air dry.'],
    avoid: ['Do not smear wet mud.', 'No bleach on denim.', 'No high heat until clear.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.denimBoundary,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-sweat-white-cotton',
    stainType: 'protein',
    materials: ['cotton'],
    title: 'Sweat on Washable White Cotton',
    safeSteps: ['Keep the area cool.', 'Rinse with cool water if washable.', 'Use mild detergent.', 'Air dry and inspect before heat.'],
    avoid: ['No dryer until clear.', 'No chlorine bleach unless separately reviewed.', 'No ammonia.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinCotton,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-chocolate-cotton',
    stainType: 'mixed_unknown',
    materials: ['cotton'],
    title: 'Chocolate on Washable Cotton',
    safeSteps: ['Lift excess gently.', 'Use cold water first because chocolate can include protein.', 'Use mild detergent if washable and colorfast.', 'Air dry and inspect.'],
    avoid: ['No hot water.', 'No dryer until clear.', 'No bleach on colored fabric.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinCotton,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-coffee-with-cream-cotton',
    stainType: 'mixed_unknown',
    materials: ['cotton'],
    title: 'Coffee With Cream on Washable Cotton',
    safeSteps: ['Blot liquid.', 'Use cool water first because cream adds protein.', 'Use mild detergent if washable and colorfast.', 'Air dry and inspect.'],
    avoid: ['No hot water.', 'No ammonia or baking soda.', 'No dryer until clear.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinTannin,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-urine-cotton',
    stainType: 'protein',
    materials: ['cotton'],
    title: 'Urine on Washable Cotton',
    safeSteps: ['Blot moisture.', 'Rinse with cool water if washable.', 'Use mild detergent.', 'Air dry and refer if odor remains.'],
    avoid: ['No heat.', 'No bleach/ammonia mixing.', 'Do not mask odor with fragrance.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinHeat,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-leather-any-stain',
    stainType: 'mixed_unknown',
    materials: ['leather'],
    title: 'Any Stain on Leather',
    safeSteps: [],
    avoid: ['Do not use water, dish soap, alcohol, acetone, bleach, or heat.', 'Do not rub.', 'Do not keep experimenting.'],
    maxVerdict: 'stop_use_pro',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.leatherBoundary,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
  },
  {
    id: 'consumer-suede-any-stain',
    stainType: 'mixed_unknown',
    materials: ['suede'],
    title: 'Any Stain on Suede or Nubuck',
    safeSteps: [],
    avoid: ['Do not wet suede.', 'Do not use soap, alcohol, solvents, oil cleaners, or bleach.', 'Do not rub the nap.'],
    maxVerdict: 'stop_use_pro',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.suedeBoundary,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
  },
  {
    id: 'consumer-silk-any-protein-dye',
    stainType: 'mixed_unknown',
    materials: ['silk'],
    title: 'Protein, Dye, or Unknown Stain on Silk',
    safeSteps: [],
    avoid: ['Do not use enzyme detergent, bleach, peroxide, hot water, or acetone.', 'Do not rub or wring.', 'Do not machine wash.'],
    maxVerdict: 'stop_use_pro',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.silkBoundary,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
  },
  {
    id: 'consumer-wool-any-protein-dye',
    stainType: 'mixed_unknown',
    materials: ['wool'],
    title: 'Protein, Dye, or Unknown Stain on Wool',
    safeSteps: [],
    avoid: ['Do not use enzyme detergent, chlorine bleach, hot water, or agitation.', 'Do not wring.', 'Do not machine dry.'],
    maxVerdict: 'stop_use_pro',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.woolBoundary,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
  },
  {
    id: 'consumer-dye-transfer-any',
    stainType: 'dye',
    materials: ['cotton', 'linen', 'denim', 'polyester', 'nylon', 'wool', 'silk', 'rayon_viscose', 'acetate', 'leather', 'suede', 'blend', 'unknown'],
    title: 'Dye Transfer or Color Bleed',
    safeSteps: [],
    avoid: ['Do not rub.', 'Do not bleach.', 'Do not use alcohol, acetone, or peroxide at home.'],
    maxVerdict: 'stop_use_pro',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.dyeInk,
    sourceSupport: 'yes',
    proChemistryInSource: true,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
  },
  {
    id: 'consumer-rust-any',
    stainType: 'rust_mineral',
    materials: ['cotton', 'linen', 'denim', 'polyester', 'nylon', 'wool', 'silk', 'rayon_viscose', 'acetate', 'blend', 'unknown'],
    title: 'Rust or Mineral Stain',
    safeSteps: [],
    avoid: ['Do not use chlorine bleach.', 'Do not use strong acids.', 'Do not heat.'],
    maxVerdict: 'stop_use_pro',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.acidFiber,
    sourceSupport: 'partial',
    proChemistryInSource: true,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-coffee-black-cotton',
    stainType: 'tannin',
    materials: ['cotton'],
    title: 'Black Coffee on Washable Cotton',
    safeSteps: ['Blot liquid with a clean white cloth; do not rub.', 'If the care label allows washing, flush cool water from the back of the stain.', 'Work a small amount of mild liquid detergent into the spot if the fabric is colorfast.', 'Rinse cool, then air dry and inspect before any heat.', 'If a faint shadow remains, repeat once; refer if it does not clear.'],
    avoid: ['No hot water; it sets the tannin.', 'No ammonia, baking soda, or other alkaline cleaners.', 'No dryer or iron until the stain is fully gone.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.tannin,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-coffee-cotton',
    stainType: 'tannin',
    materials: ['cotton'],
    title: 'Coffee on Washable Cotton',
    safeSteps: ['Blot liquid with a clean white cloth; do not rub.', 'If the care label allows washing, flush cool water from the back of the stain.', 'Work a small amount of mild liquid detergent into the spot if the fabric is colorfast.', 'Rinse cool, then air dry and inspect before any heat.', 'If a faint shadow remains, repeat once; refer if it does not clear.'],
    avoid: ['No hot water; it sets the tannin.', 'No ammonia, baking soda, or other alkaline cleaners.', 'No dryer or iron until the stain is fully gone.', 'Coffee with milk or cream is a different stain; treat separately.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.tannin,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-coffee-cream-polyester',
    stainType: 'mixed_unknown',
    materials: ['polyester'],
    title: 'Coffee With Cream on Washable Polyester',
    safeSteps: ['Blot up liquid with a clean white cloth; do not rub.', 'Rinse with cool water only, since cream adds protein that heat will set.', 'Work a small amount of mild detergent into the spot if washable and colorfast.', 'Rinse cool, air dry, and inspect before any heat.', 'If color remains, refer rather than reaching for stronger products.'],
    avoid: ['No hot water; it cooks the cream protein and sets the coffee.', 'No baking soda, ammonia, or other alkaline cleaners.', 'No dryer until the stain is fully gone.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinTannin,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-coffee-linen',
    stainType: 'tannin',
    materials: ['linen'],
    title: 'Coffee on Washable Linen',
    safeSteps: ['Blot liquid with a clean white cloth; do not rub.', 'Take structured, lined, trimmed, or dry-clean-only linen to a pro instead.', 'For simple washable linen, flush cool water from the back of the stain.', 'Work a small amount of mild detergent into the spot if colorfast.', 'Rinse cool, air dry flat, and inspect before any heat.'],
    avoid: ['No hot water; linen shrinks and the tannin sets.', 'No ammonia or baking soda.', 'No tumble drying until the stain is gone.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.tannin,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-coffee-polyester',
    stainType: 'tannin',
    materials: ['polyester'],
    title: 'Coffee on Washable Polyester',
    safeSteps: ['Blot liquid with a clean white cloth; do not rub.', 'Flush cool water from the back of the stain.', 'Work a small amount of mild detergent into the spot if washable and colorfast.', 'Rinse cool, air dry, and inspect before any heat.', 'If a faint shadow remains, repeat once; refer if it does not clear.'],
    avoid: ['No hot water; it sets the coffee and yellows polyester.', 'No baking soda or ammonia.', 'No dryer until the stain is fully gone.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.tannin,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-tea-linen',
    stainType: 'tannin',
    materials: ['linen'],
    title: 'Tea on Washable Linen',
    safeSteps: ['Blot the spill with a clean white cloth; do not rub.', 'Check the care label; structured, lined, or vintage linen should go to a pro.', 'If washable, flush cool water from the back of the stain.', 'Use a small amount of mild detergent only if colorfast.', 'Air dry flat and inspect before any heat.'],
    avoid: ['No hot water; it sets tannin.', 'No ammonia, baking soda, or alkaline cleaners.', 'No dryer or iron until the stain is gone.', 'Do not hang wet; air dry flat.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.tannin,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-tea-polyester',
    stainType: 'tannin',
    materials: ['polyester'],
    title: 'Tea on Washable Polyester',
    safeSteps: ['Blot the spill with a clean white cloth; do not rub.', 'If washable, flush cool water from the back of the stain.', 'Use a small amount of mild detergent only if colorfast.', 'Rinse cool, then air dry and inspect before any heat.'],
    avoid: ['No hot water; polyester locks tannin under heat.', 'No ammonia, baking soda, or alkaline cleaners.', 'No dryer until the stain is gone.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.tannin,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-red-wine-linen',
    stainType: 'tannin',
    materials: ['linen'],
    title: 'Red Wine on Washable Linen',
    safeSteps: ['Confirm the linen is washable and unstructured; refer dry-clean-only, lined, vintage, or high-value linen.', 'Blot wine with a clean white cloth; do not rub.', 'If the care label allows, flush cool water from the back of the stain.', 'On colored linen, hidden-hem test mild detergent and cool water before treating.', 'Work in a small amount of mild detergent without scrubbing, then launder per the care label.', 'Air dry and inspect before any heat; refer if color or a ring remains.'],
    avoid: ['No hot or boiling water.', 'No rubbing or scrubbing.', 'No oxygen bleach, peroxide, or vinegar.', 'No bleach on colored linen.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.tannin,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-red-wine-polyester',
    stainType: 'tannin',
    materials: ['polyester'],
    title: 'Red Wine on Washable Polyester',
    safeSteps: ['Blot up wine with a clean white cloth; do not rub.', 'Flip the item inside out and flush cool water through the back of the stain.', 'Work a small amount of mild detergent into the spot if washable and colorfast.', 'Rinse cool and wash on a cool cycle per the care label.', 'Air dry and inspect in daylight before any dryer heat; refer if wine remains.'],
    avoid: ['No hot water; heat sets the wine.', 'No alkaline cleaners like OxiClean or baking soda.', 'No dryer until the stain is fully clear.', 'No chlorine bleach on polyester.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.tannin,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: true,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-white-wine-cotton',
    stainType: 'tannin',
    materials: ['cotton'],
    title: 'White Wine on Washable Cotton',
    safeSteps: ['Treat even seemingly invisible fresh spills; residue can show later if heat is used before rinsing.', 'Blot the area, then hold the back of the stain under cool running water 30-60 seconds.', 'Work a small amount of mild detergent into the spot if washable and colorfast.', 'Rinse cool, air dry, and inspect before any heat.', 'Refer if a yellow ring remains after one conservative cool-water and mild-detergent pass, especially if the item was already heat-dried.'],
    avoid: ['No hot water; heat can make beverage residue harder to remove.', 'No layering of oxidizers or bleach.', 'No dryer heat until the area is clear.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.tannin,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: true,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-berry-cotton',
    stainType: 'tannin',
    materials: ['cotton'],
    title: 'Berry on Washable Cotton',
    safeSteps: ['Blot any pulp away gently; do not rub.', 'Move fast and flush cool water from the back of the stain.', 'Work a small amount of mild liquid detergent into the spot if washable and colorfast.', 'Rinse cool and repeat the detergent pass once if color remains.', 'Air dry and inspect before any heat.'],
    avoid: ['No hot water on aged or dried berry; it sets the tannin.', 'No dryer or iron until the stain is fully gone.', 'No bleach on colored cotton.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.tannin,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-berry-linen',
    stainType: 'tannin',
    materials: ['linen'],
    title: 'Berry on Washable Linen',
    safeSteps: ['Check the care label; if dry-clean-only, structured, lined, or embellished, stop and use a pro.', 'Flip inside out and flush cool water from the back; blot, do not rub.', 'On colored linen, hidden-seam test mild detergent for dye transfer first.', 'Work a small amount of mild liquid detergent into the spot.', 'Wash cool or lukewarm per care label, then air dry flat and inspect before heat.'],
    avoid: ['No hot water; it sets the stain and risks shrinkage.', 'No tumble-dry with residual color.', 'No chlorine bleach on colored linen.', 'Do not scrub or rub.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.tannin,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-berry-polyester',
    stainType: 'tannin',
    materials: ['polyester'],
    title: 'Berry on Washable Polyester',
    safeSteps: ['Check the care label; if dry-clean-only or structured, stop and use a pro.', 'Flip inside out and flush cool water from the back; blot, do not rub.', 'On colored polyester, hidden-seam test mild detergent for dye transfer first.', 'Work a small amount of mild liquid detergent into the spot.', 'Wash cool or lukewarm per care label, then air dry and inspect before the dryer.'],
    avoid: ['No hot water; it can set residual color.', 'No dryer with residual color.', 'No chlorine bleach on colored polyester.', 'Do not rub or scrub.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.tannin,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-tomato-sauce-linen',
    stainType: 'mixed_unknown',
    materials: ['linen'],
    title: 'Tomato Sauce on Washable Linen',
    safeSteps: ['Lift off solid sauce gently with a spoon edge; do not rub.', 'Blot the spot; do not rub.', 'Flush from the back with cool water if the care label allows washing.', 'Work in a little mild detergent only if the linen is colorfast (sauce has an oily component).', 'Rinse cool, then air-dry flat and inspect before any heat.'],
    avoid: ['No hot water; it sets the tomato color and tannin.', 'No baking soda, ammonia, or other alkaline cleaners.', 'No dryer or iron until the stain is gone.', 'Do not hang wet; air-dry flat.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinTannin,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-tomato-sauce-polyester',
    stainType: 'mixed_unknown',
    materials: ['polyester'],
    title: 'Tomato Sauce on Washable Polyester',
    safeSteps: ['Lift off solid sauce gently; do not rub.', 'Blot the spot.', 'Flush with cool water if the care label allows washing.', 'Work in a little mild detergent only if colorfast (polyester grips the oil).', 'Cool wash, air-dry, and inspect dry before any heat.'],
    avoid: ['No hot water; polyester locks color under heat.', 'No baking soda, ammonia, or other alkaline cleaners.', 'No hot dryer until clear; it sets the orange shadow.', 'Do not rub.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinTannin,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-barbecue-sauce-cotton',
    stainType: 'mixed_unknown',
    materials: ['cotton'],
    title: 'Barbecue Sauce on Washable Cotton',
    safeSteps: ['Scrape off solid sauce gently; do not rub.', 'Flush from the back with cool water, longer than usual, if washable (the sugar sets fast).', 'Work in a little mild detergent only if colorfast (sauce has an oily component).', 'Rinse cool, air-dry, and inspect before any heat.'],
    avoid: ['No hot water; heat caramelizes the sugar and locks the stain.', 'No baking soda, ammonia, or other alkaline cleaners.', 'No dryer, iron, or hot-sun drying until the stain is gone.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinTannin,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-soy-sauce-cotton',
    stainType: 'tannin',
    materials: ['cotton'],
    title: 'Soy Sauce on Washable Cotton',
    safeSteps: ['Check the care label; if dry-clean-only, structured, or delicate, stop and see a pro.', 'Blot or lift excess with a clean white cloth; do not rub.', 'Back-rinse with cool water if the care label allows.', 'Use a little mild detergent, testing colored fabric on a hidden spot first.', 'Air-dry and inspect before any dryer or iron.'],
    avoid: ['No hot water, dryer, or iron until the stain is gone.', 'No baking soda, ammonia, or other alkaline cleaners.', 'Do not mix cleaners or scrub aggressively.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.tannin,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-soy-sauce-linen',
    stainType: 'tannin',
    materials: ['linen'],
    title: 'Soy Sauce on Washable Linen',
    safeSteps: ['Check the care label; structured, lined, or vintage linen goes to a pro.', 'Blot or lift excess with a clean white cloth; do not rub.', 'Back-rinse with cool water if the care label allows.', 'Use a little mild detergent, testing colored fabric on a hidden spot first.', 'Air-dry flat and inspect before any heat.'],
    avoid: ['No hot water, dryer, or iron until clear.', 'No baking soda, ammonia, or other alkaline cleaners.', 'Do not over-wet structured linen or scrub.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.tannin,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-soy-sauce-polyester',
    stainType: 'tannin',
    materials: ['polyester'],
    title: 'Soy Sauce on Washable Polyester',
    safeSteps: ['Blot the spot first; do not rub.', 'Back-rinse quickly with cool water if washable; salt sets the brown color fast.', 'Work in a little mild detergent, testing colored fabric on a hidden spot first.', 'Cool wash, air-dry, and inspect dry before any heat.'],
    avoid: ['No hot water; polyester locks the brown under heat.', 'No baking soda, ammonia, or other alkaline cleaners.', 'No hot dryer until fully clear.', 'Do not rub.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.tannin,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-beer-cotton',
    stainType: 'tannin',
    materials: ['cotton'],
    title: 'Beer on Washable Cotton',
    safeSteps: ['Blot up liquid with a clean white cloth; do not rub.', 'If the care label allows washing, flush cool water from the back of the stain.', 'On colored cotton, hidden-test a little mild detergent on an inside seam first.', 'Work a small amount of mild liquid detergent into the spot with light fingertip pressure.', 'Rinse cool, then air dry and inspect before any heat.'],
    avoid: ['No hot water; it can set the tannin color.', 'No rubbing or scrubbing.', 'No dryer or iron until the stain is fully gone.', 'No bleach on colored cotton.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.tannin,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-grease-cotton',
    stainType: 'oil_grease',
    materials: ['cotton'],
    title: 'Grease on Washable Cotton',
    safeSteps: ['Lift or blot off excess grease; do not rub it deeper.', 'Cover with absorbent powder (cornstarch or baking soda); let it sit, then brush away.', 'Work a little mild detergent into the spot if the label says washable and colorfast.', 'Rinse cool and check for an oily feel; repeat the detergent step if needed.', 'Air dry and inspect in daylight before any heat.'],
    avoid: ['Do not rub the grease in deeper.', 'No dryer or iron until the spot is fully gone.', 'No solvents, mineral spirits, or paint thinner at home.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.cottonOilHold,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-grease-denim',
    stainType: 'oil_grease',
    materials: ['denim'],
    title: 'Grease on Washable Denim',
    safeSteps: ['Lift off excess grease; blot only, never rub (denim rings under scrubbing).', 'Cover with absorbent powder first; let it sit, then brush away before adding any water.', 'Dab a little mild detergent into the spot with cool water if the denim is washable.', 'Rinse cool and check; repeat the detergent step if it still feels oily.', 'Air dry fully and inspect before any heat.'],
    avoid: ['No chlorine bleach on denim (strips indigo unevenly).', 'No hot water or dryer heat until clear.', 'Do not rub or scrub the spot.', 'No solvents or degreasers at home.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.cottonOilHold,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-grease-polyester',
    stainType: 'oil_grease',
    materials: ['polyester'],
    title: 'Grease on Washable Polyester',
    safeSteps: ['Lift or blot off excess grease; do not rub.', 'Cover with absorbent powder first; let it sit, then brush away (polyester holds oil tightly).', 'Work a little mild detergent into the spot with cool water if washable and colorfast.', 'Rinse cool and check; polyester often needs a second detergent pass.', 'Air dry and inspect before any heat.'],
    avoid: ['No hot water (sets oil and yellows polyester).', 'No chlorine bleach on polyester.', 'No dryer until the spot is fully clear.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.cottonOilHold,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-grease-cooking-oil-cotton',
    stainType: 'oil_grease',
    materials: ['cotton'],
    title: 'Cooking Grease or Oil on Washable Cotton',
    safeSteps: ['Lift or blot off excess oil; do not reach for a wet cloth first (water spreads it).', 'Cover with absorbent powder; let it sit, then brush away.', 'Work a little mild detergent into the spot if the label says washable and colorfast.', 'Rinse cool and check for an oily feel; repeat the detergent step if needed.', 'Air dry and inspect in daylight before any heat.'],
    avoid: ['Do not add water before the powder step (spreads the oil).', 'No dryer or iron until the stain is gone.', 'No oxygen or chlorine bleach in this first-step protocol.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.cottonOilHold,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-grease-cooking-oil-polyester',
    stainType: 'oil_grease',
    materials: ['polyester'],
    title: 'Cooking Grease or Oil on Washable Polyester',
    safeSteps: ['Lift or blot off excess oil; do not rub.', 'Cover with absorbent powder first; let it sit, then brush away.', 'Work a little mild detergent into the spot with cool water if washable and colorfast.', 'Rinse cool and check; polyester usually needs a second detergent pass.', 'Air dry and inspect before any heat.'],
    avoid: ['No hot water (sets oil and yellows polyester).', 'No dryer or fabric softener until the spot is clear.', 'No chlorine bleach on polyester.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.cottonOilHold,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-cooking-oil-linen',
    stainType: 'oil_grease',
    materials: ['linen'],
    title: 'Cooking Oil on Washable Linen',
    safeSteps: ['Stop if the linen is structured, lined, vintage, dark-dyed, or dry-clean-only — that is a pro job.', 'On simple washable linen, lift or blot off excess oil; do not rub or spread the halo.', 'Cover fresh oil with absorbent powder; let it sit, then brush away before adding water.', 'Work a little mild detergent in gently with cool water, outside edge inward.', 'Rinse cool, air dry flat, and inspect before any heat.'],
    avoid: ['No hot water (linen shrinks).', 'No dryer or iron until the oily mark is gone.', 'No aggressive brushing or scrubbing.', 'Structured, lined, or vintage linen goes to a pro.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.cottonOilHold,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-cooking-oil-polyester',
    stainType: 'oil_grease',
    materials: ['polyester'],
    title: 'Cooking Oil on Washable Polyester',
    safeSteps: ['Lift or blot off excess oil; do not rub.', 'Cover with absorbent powder first; let it sit, then brush away (polyester grabs oil tightly).', 'Work a little mild detergent into the spot with cool water if washable and colorfast.', 'Rinse cool and check; polyester typically needs a second detergent pass.', 'Air dry and inspect before any heat.'],
    avoid: ['No hot water (sets oil and yellows polyester).', 'No dryer until fully clear.', 'No chlorine bleach on polyester.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.cottonOilHold,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-olive-oil-cotton',
    stainType: 'oil_grease',
    materials: ['cotton'],
    title: 'Olive Oil on Washable Cotton',
    safeSteps: ['Lift or blot off excess oil; do not reach for a wet cloth first.', 'Cover with absorbent powder; let it sit, then brush away.', 'Work a little mild detergent into the spot if the label says washable and colorfast.', 'Rinse cool and check for an oily feel; repeat the detergent step if needed.', 'Air dry and inspect in daylight before any heat.'],
    avoid: ['Do not add water before the powder step (spreads the oil).', 'No dryer or iron until the stain is gone.', 'No chlorine bleach on colored cotton.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.cottonOilHold,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-olive-oil-linen',
    stainType: 'oil_grease',
    materials: ['linen'],
    title: 'Olive Oil on Washable Linen',
    safeSteps: ['Stop if the linen is structured, lined, embellished, vintage, high-value, or dry-clean-only — route to a pro.', 'On simple washable linen, blot or lift excess oil; do not rub or spread the halo.', 'On colored linen, hidden-test mild detergent and cool water on a hem first.', 'Work a small amount of mild detergent into the oily area gently with cool water.', 'Wash cool per care label, air dry flat, and inspect before any heat.', 'Repeat once if improving; escalate on spreading halo, ring, or dye bleed.'],
    avoid: ['No hot water, dryer, or iron until the oil is gone.', 'No rubbing or aggressive scrubbing.', 'No solvents, oxidizers, or pro spotters at home.', 'Structured or valuable linen goes to a pro.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.cottonOilHold,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-olive-oil-polyester',
    stainType: 'oil_grease',
    materials: ['polyester'],
    title: 'Olive Oil on Washable Polyester',
    safeSteps: ['Lift or blot off excess oil; do not rub.', 'Cover with absorbent powder first; let it sit, then brush away.', 'Work a little mild detergent into the spot with cool water if washable and colorfast.', 'Rinse cool and check; polyester typically needs a second detergent pass.', 'Air dry and inspect before any heat.'],
    avoid: ['No hot water (sets oil and yellows polyester).', 'No dryer or fabric softener until the spot is clear.', 'No chlorine bleach on polyester.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.cottonOilHold,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-motor-oil-cotton',
    stainType: 'oil_grease',
    materials: ['cotton'],
    title: 'Motor Oil on Washable Cotton',
    safeSteps: ['Lift any pooled oil with a dull edge; do not rub it deeper.', 'Cover the spot with absorbent powder (cornstarch or baby powder), let it sit, then brush it away.', 'Work a small amount of mild dish or laundry detergent into the spot if the item is washable and colorfast.', 'Rinse cool and repeat the powder-and-detergent pass while the stain keeps lightening.', 'Air dry and inspect in daylight before any heat.'],
    avoid: ['No solvents, mineral spirits, or paint thinner at home.', 'No hot dryer until the stain is fully gone — heat sets oil permanently.', 'Do not rub or scrub the spot.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.cottonOilHold,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-motor-oil-denim',
    stainType: 'oil_grease',
    materials: ['denim'],
    title: 'Motor Oil on Washable Denim',
    safeSteps: ['Cover the oil with absorbent powder (cornstarch or baking soda) BEFORE adding water; let it sit, then brush it away.', 'Blot any remaining oil; do not rub, which can halo dark denim.', 'Work a small amount of mild dish detergent into the spot with cool water if the denim is washable.', 'Rinse cool and repeat the powder-and-detergent pass if oil remains.', 'Air dry fully and inspect before any heat.'],
    avoid: ['No hot water — it sets petroleum into denim.', 'No chlorine bleach on denim — it strips indigo unevenly.', 'No hot dryer until clear; do not rub or scrub.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.cottonOilHold,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-body-oil-cotton',
    stainType: 'oil_grease',
    materials: ['cotton'],
    title: 'Body Oil on Washable Cotton',
    safeSteps: ['Cover heavier spots with absorbent powder, let it sit, then brush it away.', 'Work a small amount of mild detergent into the spot if the item is washable and colorfast.', 'Let it dwell a few minutes, then rinse with cool water.', 'Air dry — line-drying in sun helps fade residual yellow on white cotton.', 'Inspect before any dryer heat and repeat the detergent pass if needed.'],
    avoid: ['No dryer heat on residual yellow — it sets permanently.', 'No peroxide or bleach in this first-step protocol.', 'Do not rub the fabric raw.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.cottonOilHold,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-body-oil-polyester',
    stainType: 'oil_grease',
    materials: ['polyester'],
    title: 'Body Oil on Washable Polyester',
    safeSteps: ['Cover the oily area with absorbent powder BEFORE water; let it sit, then brush it away.', 'Work a small amount of mild detergent into the spot with cool water if washable.', 'Let it dwell briefly, then rinse cool; touch-test and repeat if it still feels oily.', 'Wash cool with normal detergent and skip fabric softener.', 'Air dry and inspect before any heat.'],
    avoid: ['No hot water — it sets oil and yellows polyester.', 'No hot dryer until clear; no fabric softener.', 'No chlorine bleach on polyester.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.cottonOilHold,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-cosmetic-oil-cotton',
    stainType: 'oil_grease',
    materials: ['cotton'],
    title: 'Cosmetic Oil on Washable Cotton',
    safeSteps: ['Cover the spot with absorbent powder BEFORE water; let it sit, then brush it away.', 'Work a small amount of mild detergent into the spot if washable and colorfast.', 'Touch-test with a clean fingertip; if it still feels slick, repeat the detergent pass (silicone often needs two).', 'Rinse cool, then air dry the first time.', 'Inspect in daylight before any dryer heat.'],
    avoid: ['No hot dryer with residual oil — it polymerizes into cotton.', 'No solvents or peroxide at home.', 'Do not rub the spot or skip the second detergent pass on slick serums.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.cottonOilHold,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-cosmetic-oil-polyester',
    stainType: 'oil_grease',
    materials: ['polyester'],
    title: 'Cosmetic Oil on Washable Polyester',
    safeSteps: ['Cover the spot with absorbent powder BEFORE water; let it sit, then brush it away.', 'Work a small amount of mild detergent into the spot with cool water if washable.', 'Touch-test with a clean fingertip; if still slick, repeat the detergent pass (silicone often needs two).', 'Wash cool with normal detergent and skip fabric softener.', 'Air dry and inspect before any heat.'],
    avoid: ['No hot water — it sets oil and yellows polyester.', 'No hot dryer until clear; no fabric softener.', 'Do not skip the second detergent pass on slick serums.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.cottonOilHold,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-butter-linen',
    stainType: 'oil_grease',
    materials: ['linen'],
    title: 'Butter on Washable Linen',
    safeSteps: ['Lift excess butter gently with a dull edge; do not rub into the weave.', 'Blot any oily residue with a clean white cloth.', 'On colored linen, hidden-test mild detergent and cool water on an inside seam first.', 'Work a small amount of mild liquid detergent into the spot if washable and colorfast.', 'Wash cool or lukewarm per the care label, then rinse.', 'Air dry flat and inspect for residual oil before any heat.'],
    avoid: ['No hot water on uncertain, colored, or high-value linen.', 'No tumble-dry until the stain is fully gone; heat sets oil.', 'No chlorine bleach on colored linen.', 'No rubbing, scrubbing, or solvents.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.cottonOilHold,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-butter-polyester',
    stainType: 'oil_grease',
    materials: ['polyester'],
    title: 'Butter on Washable Polyester',
    safeSteps: ['Lift excess butter gently with a dull edge; do not rub it deeper.', 'Blot any oily residue with a clean white cloth.', 'On colored polyester, hidden-test mild detergent and cool water on an inside seam first.', 'Work a small amount of mild liquid detergent into the spot if washable and colorfast.', 'Wash per the care label, favoring cool or lukewarm; expect a repeat pass since polyester holds oil.', 'Air dry and inspect for residual oil before any dryer heat.'],
    avoid: ['No machine-dry until the stain is gone; heat sets oil into polyester.', 'No chlorine bleach on colored polyester.', 'No rubbing or scrubbing.', 'No solvents at home.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.cottonOilHold,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-chocolate-polyester',
    stainType: 'mixed_unknown',
    materials: ['polyester'],
    title: 'Chocolate on Washable Polyester',
    safeSteps: ['Lift off solid chocolate gently with the edge of a spoon; do not rub it in.', 'Blot from the back; flush with cool water first because chocolate includes protein.', 'Work a small amount of mild dish or liquid detergent into the spot with light pressure if the label says washable and the fabric is colorfast.', 'Rinse cool, then air dry and inspect before any heat.'],
    avoid: ['No hot water or dryer heat (sets the stain and yellows polyester).', 'No alkaline cleaners like ammonia or baking soda.', 'No bleach on colored polyester.', 'Do not scrub oily residue deeper.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinTannin,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-lipstick-cotton',
    stainType: 'mixed_unknown',
    materials: ['cotton'],
    title: 'Lipstick on Washable Cotton',
    safeSteps: ['Lift solid lipstick off with a dull edge; do not rub.', 'Place a clean white cloth under the stain to catch lifted color.', 'Dab on absorbent powder (cornstarch) to pull up oil, wait, then brush it away.', 'Use a small amount of mild detergent only if washable and colorfast; blot gently from the back.', 'Rinse cool, air dry, and inspect before any heat.'],
    avoid: ['Do not rub — it grinds pigment into the weave.', 'No solvents, alcohol, or bleach at home.', 'No dryer heat until the stain is gone.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinTannin,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-lipstick-polyester',
    stainType: 'mixed_unknown',
    materials: ['polyester'],
    title: 'Lipstick on Washable Polyester',
    safeSteps: ['Lift excess lipstick with a dull plastic edge; never rub.', 'Cover the spot with absorbent powder (cornstarch) to pull up oil, wait, then brush it away.', 'Blot from the back with a clean white cloth placed underneath.', 'Use a small amount of mild detergent in cool water only if colorfast; let it dwell, then rinse cool.', 'Air dry and inspect in daylight before any heat.'],
    avoid: ['No hot water — it sets the oil and locks the dye.', 'No dryer heat or fabric softener until cleared.', 'Do not rub — it pushes pigment into the fiber.', 'No solvents or bleach at home.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinTannin,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-makeup-cotton',
    stainType: 'mixed_unknown',
    materials: ['cotton'],
    title: 'Makeup on Washable Cotton',
    safeSteps: ['Scrape off any cakey makeup with a dull edge; do not rub.', 'Place a clean white cloth under the stain to catch lifted pigment.', 'Dab on absorbent powder (cornstarch) to lift oil, wait, then brush it away.', 'Use a small amount of mild detergent only if washable and colorfast; blot gently from the back.', 'Rinse cool, air dry, and inspect before any heat.'],
    avoid: ['Do not rub — it spreads pigment into clean fabric.', 'No solvents, alcohol, or bleach at home.', 'No dryer heat until the stain is gone.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinTannin,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-makeup-polyester',
    stainType: 'mixed_unknown',
    materials: ['polyester'],
    title: 'Foundation and Makeup on Washable Polyester',
    safeSteps: ['Scrape excess foundation off with a dull plastic edge; never rub.', 'Cover the spot with absorbent powder (cornstarch) to pull up oil, wait, then brush it away.', 'Blot from the back with a clean white cloth placed underneath.', 'Use a small amount of mild detergent in cool water only if colorfast; repeat gently if it still feels oily.', 'Rinse cool, air dry, and inspect in daylight before any heat.'],
    avoid: ['No hot water — it sets the oil and yellows polyester.', 'No dryer heat or fabric softener until cleared.', 'Do not rub — it pushes pigment into the fiber.', 'No solvents or bleach at home.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinTannin,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-milk-cotton',
    stainType: 'protein',
    materials: ['cotton'],
    title: 'Milk on Washable Cotton',
    safeSteps: ['Lift or blot excess milk with a clean white cloth; do not rub.', 'If the care label allows washing, rinse cool water through from the back of the stain.', 'Work a small amount of mild liquid detergent into the spot, but only if washable and colorfast.', 'Rinse cool, then air dry and inspect before any heat.', 'If odor or a faint mark remains after drying, stop and refer to a pro rather than reaching for heat.'],
    avoid: ['No hot water; heat sets milk protein into cotton.', 'No dryer or iron until the stain is fully gone.', 'No bleach on colored fabric.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinCotton,
    sourceSupport: 'partial',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-milk-polyester',
    stainType: 'protein',
    materials: ['polyester'],
    title: 'Milk on Washable Polyester',
    safeSteps: ['Blot or lift excess milk with a clean white cloth; do not rub.', 'Rinse with cool water only.', 'Use a small amount of mild detergent if the item is washable and colorfast.', 'Air dry and inspect before any heat; if a mark or odor remains after drying, stop and refer rather than repeating hot treatment.'],
    avoid: ['No hot water; heat can set the protein component and make residue harder to remove.', 'No dryer until the stain is clear.', 'No repeated scrubbing.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinCotton,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: true,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-egg-cotton',
    stainType: 'protein',
    materials: ['cotton'],
    title: 'Egg on Washable Cotton',
    safeSteps: ['Lift solid egg or yolk gently with a dull edge; do not rub.', 'If washable, rinse cool water through from the back of the stain.', 'Work in a small amount of mild detergent, but only if colorfast.', 'Rinse cool, then air dry and inspect before any heat.', 'Repeat the cool rinse once if a mark remains; refer to a pro if it does not clear.'],
    avoid: ['No warm or hot water; it cooks egg protein into the fiber.', 'No iron, steam, or dryer until the stain is gone.', 'No chlorine bleach as a protein treatment.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinCotton,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-egg-polyester',
    stainType: 'protein',
    materials: ['polyester'],
    title: 'Egg on Washable Polyester',
    safeSteps: ['Scrape thick egg off the surface gently with a dull edge; do not rub.', 'Blot with a cloth dampened in cool water; cool only.', 'Use a small amount of mild detergent if the item is washable and colorfast.', 'Air dry and inspect before any heat; refer to a pro if the egg was already cooked or hot-washed.'],
    avoid: ['No warm or hot water; even warm water cooks raw egg into polyester.', 'No dryer until the stain is clear.', 'No scrubbing the spot.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinCotton,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: true,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-grass-cotton',
    stainType: 'mixed_unknown',
    materials: ['cotton'],
    title: 'Grass Stain on Washable Cotton',
    safeSteps: ['Lift loose grass and dirt with a dull spoon; do not rub it in.', 'Flush from the back with cold water only if the care label allows washing.', 'Work a small amount of mild liquid detergent into the spot with light fingertip pressure if colorfast.', 'Rinse cool, then air dry fully and inspect in daylight before any heat.', 'If green remains after washing, repeat the cool detergent pass or refer; do not dry.'],
    avoid: ['No warm or hot water; it sets the plant protein.', 'No dryer or iron until the stain is fully gone.', 'No bleach on colored cotton.', 'Do not scrub the spot.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinTannin,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-grass-polyester',
    stainType: 'mixed_unknown',
    materials: ['polyester'],
    title: 'Grass Stain on Washable Polyester',
    safeSteps: ['Lift loose grass gently; do not rub it deeper.', 'Blot with a white cloth dampened in cool water; press, lift, rotate.', 'Work in a small amount of mild detergent with cool water if colorfast, then rinse cool.', 'Air dry only and inspect in daylight before any heat.', 'If green remains, repeat the cool detergent pass or refer; never put it in the dryer.'],
    avoid: ['No hot water; it locks the green into polyester permanently.', 'No dryer heat until the stain is gone; it sets the green and yellows the fabric.', 'No chlorine bleach on polyester.', 'No fabric softener; it coats the fiber and blocks cleaning.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinTannin,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-mud-cotton',
    stainType: 'particulate',
    materials: ['cotton'],
    title: 'Mud on Washable Cotton',
    safeSteps: ['Let wet mud dry first so loose soil can be lifted, not smeared.', 'Gently brush or lift loose dry mud with a soft brush or spoon edge; do not grind it in.', 'Rinse from the back with cool water if the care label allows washing.', 'Work in a little mild detergent; on colored cotton, hidden-test on a seam first and stop if dye transfers.', 'Wash per the care label, then air dry and inspect before any heat.'],
    avoid: ['Do not grind or scrub mud into the weave.', 'No hot water as the first step.', 'No dryer or iron until the mud is gone after air-dry inspection.', 'No bleach on colored cotton.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.denimBoundary,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-sweat-cotton',
    stainType: 'protein',
    materials: ['cotton'],
    title: 'Sweat on Washable Cotton',
    safeSteps: ['Turn the item inside out and rinse fresh sweat with cool water from the back of the fabric.', 'If the care label allows washing, work a small amount of mild detergent into the area with light pressure.', 'Let it sit briefly in cool water only, then rinse cool.', 'Air dry fully and inspect before any heat.'],
    avoid: ['No warm or hot water; it sets the protein.', 'No dryer or iron until the stain is gone.', 'No rubbing alcohol on sweat.', 'No bleach unless separately reviewed for white cotton.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinCotton,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-sweat-polyester',
    stainType: 'protein',
    materials: ['polyester'],
    title: 'Sweat on Washable Polyester',
    safeSteps: ['Soak the garment in cool water with a little mild detergent; keep it cool only.', 'Work mild detergent into any visible pit marks with light fingertip pressure.', 'Rinse cool, and repeat the cool soak once if odor lingers.', 'Air dry fully; do not tumble dry.'],
    avoid: ['No hot water; it sets the protein and odor.', 'No tumble dry; heat sets residual odor.', 'No fabric softener on athletic wear.', 'No rubbing alcohol on sweat.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinCotton,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
  {
    id: 'consumer-sweat-stain-cotton',
    stainType: 'protein',
    materials: ['cotton'],
    title: 'Set Sweat Stain on Washable Cotton',
    safeSteps: ['Check the care label; if dry-clean-only, structured, vintage, or high-value, stop and use a pro.', 'For washable cotton, rinse the residue with cool water; never hot.', 'Work a small amount of mild detergent into the spot and let it dwell briefly.', 'Wash cool per the care label, air dry fully, and inspect before any heat.'],
    avoid: ['No hot water until the stain is gone.', 'No bleach, peroxide, or acids at home.', 'No dryer or iron until clear.', 'Test colored cotton on a hidden seam first.'],
    maxVerdict: 'diy_with_constraints',
    consumerSafe: true,
    sources: PHASE0_EVIDENCE.proteinCotton,
    sourceSupport: 'yes',
    proChemistryInSource: false,
    phase0: true,
    phase0Fixture: true,
    publishReady: false,
    unsupportedConsumerStepClaims: false,
  },
]

const ANY_STOP_MATERIALS = new Set<Material>(['silk', 'wool', 'leather', 'suede'])

export const CARD_MATCH_TERMS: Record<string, string[]> = {
  'consumer-blood-cotton-fresh': ['blood'],
  'consumer-blood-polyester-fresh': ['blood'],
  'consumer-coffee-cotton-black': ['coffee', 'black coffee'],
  'consumer-tea-cotton': ['tea'],
  'consumer-red-wine-cotton': ['red wine', 'wine'],
  'consumer-juice-cotton': ['juice', 'fruit juice'],
  'consumer-tomato-cotton': ['tomato', 'tomato sauce'],
  'consumer-cooking-oil-cotton': ['cooking oil', 'vegetable oil', 'olive oil', 'canola oil', 'frying oil', 'food oil', 'kitchen grease', 'bacon grease'],
  'consumer-butter-cotton': ['butter'],
  'consumer-grass-denim': ['grass'],
  'consumer-mud-denim': ['mud', 'soil', 'dirt'],
  'consumer-sweat-white-cotton': ['sweat', 'perspiration'],
  'consumer-chocolate-cotton': ['chocolate'],
  'consumer-coffee-with-cream-cotton': ['coffee with cream', 'cream in coffee', 'coffee and cream'],
  'consumer-urine-cotton': ['urine', 'pee'],
  'consumer-dye-transfer-any': ['dye transfer', 'color bleed', 'colour bleed', 'ink', 'marker', 'hair dye'],
  'consumer-rust-any': ['rust', 'iron stain', 'mineral'],
  'consumer-coffee-black-cotton': ['black coffee', 'coffee'],
  'consumer-coffee-cotton': ['coffee', 'coffee stain'],
  'consumer-coffee-cream-polyester': ['coffee with cream', 'latte', 'cappuccino', 'cream in coffee'],
  'consumer-coffee-linen': ['coffee'],
  'consumer-coffee-polyester': ['coffee'],
  'consumer-tea-linen': ['tea'],
  'consumer-tea-polyester': ['tea'],
  'consumer-red-wine-linen': ['red wine', 'wine'],
  'consumer-red-wine-polyester': ['red wine', 'wine'],
  'consumer-white-wine-cotton': ['white wine', 'wine'],
  'consumer-berry-cotton': ['berry', 'blueberry', 'blackberry', 'raspberry', 'strawberry', 'mulberry'],
  'consumer-berry-linen': ['berry', 'blueberry', 'blackberry', 'raspberry', 'strawberry'],
  'consumer-berry-polyester': ['berry', 'blueberry', 'blackberry', 'raspberry', 'strawberry'],
  'consumer-tomato-sauce-linen': ['tomato', 'tomato sauce', 'marinara', 'spaghetti sauce', 'pasta sauce', 'pizza sauce'],
  'consumer-tomato-sauce-polyester': ['tomato', 'tomato sauce', 'marinara', 'spaghetti sauce', 'pasta sauce', 'pizza sauce'],
  'consumer-barbecue-sauce-cotton': ['barbecue sauce', 'bbq sauce', 'bbq', 'barbecue'],
  'consumer-soy-sauce-cotton': ['soy sauce', 'soy'],
  'consumer-soy-sauce-linen': ['soy sauce', 'soy'],
  'consumer-soy-sauce-polyester': ['soy sauce', 'soy'],
  'consumer-beer-cotton': ['beer', 'ale', 'lager'],
  'consumer-grease-cotton': ['grease', 'kitchen grease', 'bacon grease', 'cooking grease', 'pan grease'],
  'consumer-grease-denim': ['grease', 'kitchen grease', 'cooking grease', 'grease on jeans'],
  'consumer-grease-polyester': ['grease', 'kitchen grease', 'cooking grease'],
  'consumer-grease-cooking-oil-cotton': ['cooking grease', 'cooking oil', 'kitchen grease', 'grease', 'frying oil'],
  'consumer-grease-cooking-oil-polyester': ['cooking grease', 'cooking oil', 'kitchen grease', 'grease', 'frying oil'],
  'consumer-cooking-oil-linen': ['cooking oil', 'vegetable oil', 'canola oil', 'frying oil', 'food oil'],
  'consumer-cooking-oil-polyester': ['cooking oil', 'vegetable oil', 'canola oil', 'frying oil', 'peanut oil'],
  'consumer-olive-oil-cotton': ['olive oil', 'salad dressing', 'salad oil'],
  'consumer-olive-oil-linen': ['olive oil', 'salad dressing', 'salad oil'],
  'consumer-olive-oil-polyester': ['olive oil', 'salad dressing', 'salad oil'],
  'consumer-motor-oil-cotton': ['motor oil', 'engine oil', 'grease'],
  'consumer-motor-oil-denim': ['motor oil', 'engine oil', 'grease'],
  'consumer-body-oil-cotton': ['body oil', 'sebum', 'collar ring', 'pillowcase yellow'],
  'consumer-body-oil-polyester': ['body oil', 'sebum', 'collar ring', 'cuff ring'],
  'consumer-cosmetic-oil-cotton': ['cosmetic oil', 'serum', 'body oil', 'hair oil', 'massage oil', 'face oil'],
  'consumer-cosmetic-oil-polyester': ['cosmetic oil', 'serum', 'body oil', 'hair oil', 'face oil'],
  'consumer-butter-linen': ['butter'],
  'consumer-butter-polyester': ['butter'],
  'consumer-chocolate-polyester': ['chocolate'],
  'consumer-lipstick-cotton': ['lipstick', 'lip gloss', 'lip stain'],
  'consumer-lipstick-polyester': ['lipstick', 'lip gloss', 'lip stain'],
  'consumer-makeup-cotton': ['makeup', 'foundation', 'concealer', 'bb cream', 'blush', 'bronzer'],
  'consumer-makeup-polyester': ['makeup', 'foundation', 'concealer', 'bb cream', 'blush', 'bronzer'],
  'consumer-milk-cotton': ['milk', 'dairy'],
  'consumer-milk-polyester': ['milk', 'dairy'],
  'consumer-egg-cotton': ['egg'],
  'consumer-egg-polyester': ['egg'],
  'consumer-grass-cotton': ['grass', 'grass stain'],
  'consumer-grass-polyester': ['grass', 'grass stain'],
  'consumer-mud-cotton': ['mud', 'soil', 'dirt'],
  'consumer-sweat-cotton': ['sweat', 'perspiration', 'sweat stain', 'pit stain', 'yellow pit'],
  'consumer-sweat-polyester': ['sweat', 'perspiration', 'sweat odor', 'pit stain', 'funk'],
  'consumer-sweat-stain-cotton': ['sweat stain', 'perspiration stain', 'yellow underarm', 'sweat mark'],
}

function cardSpecificityScore(card: ConsumerCard, input: NormalizedSolveInput): number {
  return (CARD_MATCH_TERMS[card.id] ?? []).reduce((score, term) => (containsUnnegatedTerm(input.stainDescription, term) ? score + 1 : score), 0)
}

export function findConsumerCard(input: NormalizedSolveInput): ConsumerCard | null {
  const exactCandidates = CONSUMER_CARDS_PHASE0.filter((card) => card.stainType === input.stainType && card.materials.includes(input.material))
  if (exactCandidates.length > 0) {
    const ranked = exactCandidates
      .map((card) => ({ card, score: cardSpecificityScore(card, input) }))
      .sort((a, b) => b.score - a.score)
    if (ranked[0].score > 0) return ranked[0].card
  }

  if (ANY_STOP_MATERIALS.has(input.material)) {
    return (
      CONSUMER_CARDS_PHASE0.find((card) => card.materials.length === 1 && card.materials[0] === input.material && card.safeSteps.length === 0) ??
      null
    )
  }

  if (input.stainType === 'dye' || input.stainType === 'ink') {
    return CONSUMER_CARDS_PHASE0.find((card) => card.id === 'consumer-dye-transfer-any') ?? null
  }

  if (input.stainType === 'rust_mineral') {
    return CONSUMER_CARDS_PHASE0.find((card) => card.id === 'consumer-rust-any' && card.materials.includes(input.material)) ?? null
  }

  return null
}
