import type { Lesson, QuizQuestion } from './module1'

export const MODULE_2_META = {
  id: 'module-2',
  number: 2,
  title: 'Stain Families',
  titleEs: 'Familias de Manchas',
  description: 'Classify any stain into its chemical family and understand what breaks each bond.',
  descriptionEs: 'Clasifica cualquier mancha en su familia química y entiende qué rompe cada enlace.',
  icon: '🧪',
  color: '#22c55e',
  lessonCount: 7,
  estimatedMinutes: 25,
  passThreshold: 0.8,
}

export const MODULE_2_LESSONS: Lesson[] = [
  {
    id: 'l1',
    title: 'The 6 Stain Families',
    titleEs: 'Las 6 Familias de Manchas',
    icon: '🎯',
    objective: 'Learn the 6 chemical families every stain belongs to and why classification matters.',
    objectiveEs: 'Aprende las 6 familias químicas a las que pertenece cada mancha y por qué la clasificación importa.',
    sections: [
      {
        heading: 'Why Classification Matters',
        headingEs: 'Por Qué Importa la Clasificación',
        body: 'Every stain in the world belongs to one of six chemical families. Know the family, and you know which agent to reach for. Wrong family = wrong agent = potential damage. This is the single most important skill in spotting.',
        bodyEs: 'Cada mancha en el mundo pertenece a una de seis familias químicas. Conoce la familia, y sabrás qué agente usar. Familia incorrecta = agente incorrecto = daño potencial. Esta es la habilidad más importante del spotting.',
        visual: 'key-concept',
      },
      {
        heading: 'The Six Families',
        headingEs: 'Las Seis Familias',
        body: '1. Protein — blood, sweat, milk, egg\n2. Tannin — coffee, tea, wine, fruit juice\n3. Dye — color transfer, ink, makeup\n4. Oil/Grease — cooking oil, butter, cosmetics\n5. Combination — lipstick (dye + oil), chocolate (protein + tannin + oil)\n6. Oxidized/Set — old stains that have chemically changed',
        bodyEs: '1. Proteína — sangre, sudor, leche, huevo\n2. Tanino — café, té, vino, jugo de fruta\n3. Tinte — transferencia de color, tinta, maquillaje\n4. Aceite/Grasa — aceite de cocina, mantequilla, cosméticos\n5. Combinación — labial (tinte + aceite), chocolate (proteína + tanino + aceite)\n6. Oxidada/Fijada — manchas viejas que han cambiado químicamente',
        visual: 'key-concept',
      },
      {
        heading: 'The Decision Rule',
        headingEs: 'La Regla de Decisión',
        body: 'When you look at a stain, your first job is to classify it. Not treat it — classify it. Once you know the family, the chemistry tells you the agent. This is the bridge between observation (Module 1) and treatment.',
        bodyEs: 'Cuando ves una mancha, tu primer trabajo es clasificarla. No tratarla — clasificarla. Una vez que conoces la familia, la química te dice el agente. Este es el puente entre la observación (Módulo 1) y el tratamiento.',
        visual: 'tip',
      },
    ],
    keyTakeaway: 'Every stain belongs to one of six families. Identify the family first — then the chemistry tells you the agent.',
    keyTakeawayEs: 'Cada mancha pertenece a una de seis familias. Identifica la familia primero — luego la química te dice el agente.',
  },
  {
    id: 'l2',
    title: 'Protein Stains',
    titleEs: 'Manchas de Proteína',
    icon: '🥩',
    objective: 'Understand protein stain chemistry and why heat is the enemy.',
    objectiveEs: 'Entender la química de las manchas de proteína y por qué el calor es el enemigo.',
    sections: [
      {
        heading: 'What Are Protein Stains?',
        headingEs: '¿Qué Son las Manchas de Proteína?',
        body: 'Proteins are chains of amino acids held together by peptide bonds. When these land on fabric — blood, sweat, milk, egg, body fluids — the protein molecules bond to the fiber. Fresh protein stains are water-soluble. Set protein stains are nearly permanent.',
        bodyEs: 'Las proteínas son cadenas de aminoácidos unidos por enlaces peptídicos. Cuando caen en la tela — sangre, sudor, leche, huevo, fluidos corporales — las moléculas de proteína se unen a la fibra. Las manchas frescas de proteína son solubles en agua. Las manchas fijadas son casi permanentes.',
      },
      {
        heading: 'The #1 Rule: No Heat',
        headingEs: 'La Regla #1: Sin Calor',
        body: 'Heat denatures protein — it changes the molecular structure permanently, like cooking an egg. Once a protein stain is heated (hot water, dryer, steam, iron), the protein bonds to the fiber permanently. This is why blood set with hot water can never be fully removed. Always use COLD water on protein stains.',
        bodyEs: 'El calor desnaturaliza la proteína — cambia la estructura molecular permanentemente, como cocinar un huevo. Una vez que una mancha de proteína se calienta (agua caliente, secadora, vapor, plancha), la proteína se une a la fibra permanentemente. Por eso la sangre fijada con agua caliente nunca se puede eliminar por completo. Siempre usa agua FRÍA en manchas de proteína.',
        visual: 'warning',
      },
      {
        heading: 'Treatment Approach',
        headingEs: 'Enfoque de Tratamiento',
        body: 'First-line agent: enzyme-based protein formula. Enzymes break peptide bonds — they literally digest the protein. Cold water flush first, then apply protein formula, allow dwell time. For stubborn protein: ammonia (alkaline) helps break bonds, but test on delicates first. Never use enzymes on wool or silk without testing — enzymes can digest protein fibers too.',
        bodyEs: 'Agente de primera línea: fórmula de proteína a base de enzimas. Las enzimas rompen los enlaces peptídicos — literalmente digieren la proteína. Enjuague con agua fría primero, luego aplica la fórmula de proteína, permite tiempo de acción. Para proteína persistente: amoníaco (alcalino) ayuda a romper enlaces, pero prueba en telas delicadas primero. Nunca uses enzimas en lana o seda sin probar — las enzimas también pueden digerir fibras de proteína.',
        visual: 'tip',
      },
      {
        heading: 'Real Scenario: Blood on a White Shirt',
        headingEs: 'Escenario Real: Sangre en Camisa Blanca',
        body: 'Customer brings in a white cotton dress shirt with a blood stain on the collar. It\'s been there a few days. Your approach: Cold water flush → protein formula with 10-minute dwell → flush again → check. If still visible, the blood has partially set — try hydrogen peroxide (oxidizing bleach) as a second step, but ONLY on white cotton. On colored fabric, peroxide could bleach the dye.',
        bodyEs: 'Un cliente trae una camisa blanca de algodón con una mancha de sangre en el cuello. Ha estado ahí unos días. Tu enfoque: Enjuague con agua fría → fórmula de proteína con 10 minutos de acción → enjuagar de nuevo → verificar. Si aún es visible, la sangre se ha fijado parcialmente — prueba peróxido de hidrógeno como segundo paso, pero SOLO en algodón blanco. En tela de color, el peróxido podría blanquear el tinte.',
        visual: 'scenario',
      },
    ],
    keyTakeaway: 'Protein stains need cold water and enzymes. Heat makes them permanent. Never use hot water on blood, sweat, milk, or egg.',
    keyTakeawayEs: 'Las manchas de proteína necesitan agua fría y enzimas. El calor las hace permanentes. Nunca uses agua caliente en sangre, sudor, leche o huevo.',
  },
  {
    id: 'l3',
    title: 'Tannin Stains',
    titleEs: 'Manchas de Tanino',
    icon: '🍷',
    objective: 'Understand tannin chemistry and why timing matters most.',
    objectiveEs: 'Entender la química del tanino y por qué el tiempo es lo más importante.',
    sections: [
      {
        heading: 'What Are Tannin Stains?',
        headingEs: '¿Qué Son las Manchas de Tanino?',
        body: 'Tannins are polyphenolic compounds found in plants. They bind to proteins and other molecules through complex cross-linking and hydrogen bonding. Common tannin stains: coffee, tea, red wine, beer, fruit juice, cola, tomato sauce.',
        bodyEs: 'Los taninos son compuestos polifenólicos que se encuentran en las plantas. Se unen a proteínas y otras moléculas a través de entrecruzamiento complejo y enlaces de hidrógeno. Manchas comunes de tanino: café, té, vino tinto, cerveza, jugo de fruta, cola, salsa de tomate.',
      },
      {
        heading: 'Time Is Everything',
        headingEs: 'El Tiempo Lo Es Todo',
        body: 'Fresh tannin stains are relatively easy to remove. But oxidation changes everything — exposure to air and time causes tannins to polymerize (bond together into larger molecules). A fresh coffee stain takes 2 minutes to treat. A week-old coffee stain may take 20 minutes and stronger chemistry. A month-old coffee stain may be permanent.',
        bodyEs: 'Las manchas frescas de tanino son relativamente fáciles de eliminar. Pero la oxidación lo cambia todo — la exposición al aire y el tiempo causa que los taninos se polimericen (se unan en moléculas más grandes). Una mancha fresca de café toma 2 minutos. Una mancha de café de una semana puede tomar 20 minutos y química más fuerte. Una mancha de café de un mes puede ser permanente.',
        visual: 'warning',
      },
      {
        heading: 'Treatment Approach',
        headingEs: 'Enfoque de Tratamiento',
        body: 'First-line agent: tannin formula (acid-based). The acid breaks the tannin-protein cross-links. For fresh stains: flush with water, apply tannin formula, short dwell. For set tains: may need oxidizing bleach after tannin formula. Important: do NOT use soap or detergent first on tannin stains — soap can set tannins by creating soap-tannin complexes.',
        bodyEs: 'Agente de primera línea: fórmula de tanino (a base de ácido). El ácido rompe los entrecruzamientos tanino-proteína. Para manchas frescas: enjuagar con agua, aplicar fórmula de tanino, acción breve. Para manchas fijadas: puede necesitar blanqueador oxidante después de la fórmula de tanino. Importante: NO uses jabón o detergente primero en manchas de tanino — el jabón puede fijar los taninos creando complejos jabón-tanino.',
        visual: 'tip',
      },
    ],
    keyTakeaway: 'Tannin stains get harder with time. Treat fast with acid-based tannin formula. Never use soap first — it sets tannins.',
    keyTakeawayEs: 'Las manchas de tanino se vuelven más difíciles con el tiempo. Trata rápido con fórmula de tanino a base de ácido. Nunca uses jabón primero — fija los taninos.',
  },
  {
    id: 'l4',
    title: 'Dye Stains',
    titleEs: 'Manchas de Tinte',
    icon: '🎨',
    objective: 'Understand why dye stains are the hardest and when to escalate.',
    objectiveEs: 'Entender por qué las manchas de tinte son las más difíciles y cuándo escalar.',
    sections: [
      {
        heading: 'What Are Dye Stains?',
        headingEs: '¿Qué Son las Manchas de Tinte?',
        body: 'Dye stains are pigments or colorants that have transferred onto fabric where they don\'t belong. Sources: color bleeding from other garments, ink (ballpoint, felt tip, permanent marker), makeup (foundation, lipstick dye component), hair dye, fabric dye from new unwashed garments.',
        bodyEs: 'Las manchas de tinte son pigmentos o colorantes que se han transferido a la tela donde no pertenecen. Fuentes: sangrado de color de otras prendas, tinta (bolígrafo, marcador), maquillaje (base, componente de tinte del labial), tinte de cabello, tinte de tela de prendas nuevas sin lavar.',
      },
      {
        heading: 'Why These Are the Hardest',
        headingEs: 'Por Qué Son las Más Difíciles',
        body: 'Dyes are designed to bond permanently to fibers. That\'s their job. When a dye transfers to the wrong fabric, you\'re fighting a molecule that was engineered to be permanent. Many dye stains cannot be fully removed without also removing the garment\'s original dye. This is where judgment matters most.',
        bodyEs: 'Los tintes están diseñados para unirse permanentemente a las fibras. Ese es su trabajo. Cuando un tinte se transfiere a la tela incorrecta, estás luchando contra una molécula que fue diseñada para ser permanente. Muchas manchas de tinte no se pueden eliminar completamente sin también eliminar el tinte original de la prenda. Aquí es donde el juicio importa más.',
        visual: 'warning',
      },
      {
        heading: 'Treatment Approach',
        headingEs: 'Enfoque de Tratamiento',
        body: 'First: identify the dye type (water-based, solvent-based, reactive). For ink: try POG (paint-oil-grease remover) or amyl acetate. For color bleed: reducing bleach may work on white fabrics. For makeup dye: POG first for the oil component, then work on the dye residue. Critical rule: ALWAYS test. Dye removal agents can strip the garment\'s own color.',
        bodyEs: 'Primero: identifica el tipo de tinte (a base de agua, a base de solvente, reactivo). Para tinta: prueba POG (removedor de pintura-aceite-grasa) o acetato de amilo. Para sangrado de color: blanqueador reductor puede funcionar en telas blancas. Para tinte de maquillaje: POG primero para el componente de aceite, luego trabaja en el residuo de tinte. Regla crítica: SIEMPRE prueba. Los agentes de remoción de tinte pueden quitar el color propio de la prenda.',
        visual: 'tip',
      },
      {
        heading: 'When to Say No',
        headingEs: 'Cuándo Decir No',
        body: 'Some dye stains cannot be safely removed. If the dye has bonded to the fiber and the only way to remove it would damage the garment\'s original color — that\'s when you escalate or decline. A $200 jacket with a small ink mark is better returned with the mark than returned with a bleach spot. Know your limits. Communicate them clearly.',
        bodyEs: 'Algunas manchas de tinte no se pueden eliminar de manera segura. Si el tinte se ha unido a la fibra y la única forma de eliminarlo dañaría el color original de la prenda — ahí es cuando escalas o rechazas. Una chaqueta de $200 con una pequeña marca de tinta es mejor devolverla con la marca que con una mancha de blanqueador. Conoce tus límites. Comunícalos claramente.',
        visual: 'scenario',
      },
    ],
    keyTakeaway: 'Dye stains are engineered to be permanent. Test everything. Know when to stop. A bleach spot is worse than the original stain.',
    keyTakeawayEs: 'Las manchas de tinte están diseñadas para ser permanentes. Prueba todo. Sabe cuándo parar. Una mancha de blanqueador es peor que la mancha original.',
  },
  {
    id: 'l5',
    title: 'Oil & Grease Stains',
    titleEs: 'Manchas de Aceite y Grasa',
    icon: '🛢️',
    objective: 'Master the dry-side approach to oil-based stains.',
    objectiveEs: 'Dominar el enfoque del lado seco para manchas a base de aceite.',
    sections: [
      {
        heading: 'What Are Oil/Grease Stains?',
        headingEs: '¿Qué Son las Manchas de Aceite/Grasa?',
        body: 'Oils and greases are hydrophobic — they repel water. That\'s why water alone won\'t remove them. They\'re made of long hydrocarbon chains with fatty acids. Common sources: cooking oil, butter, salad dressing, body oils, motor oil, cosmetic creams, sunscreen, hair products.',
        bodyEs: 'Los aceites y grasas son hidrofóbicos — repelen el agua. Por eso el agua sola no los elimina. Están hechos de cadenas largas de hidrocarburos con ácidos grasos. Fuentes comunes: aceite de cocina, mantequilla, aderezo, aceites corporales, aceite de motor, cremas cosméticas, protector solar, productos para el cabello.',
      },
      {
        heading: 'Dry-Side Thinking',
        headingEs: 'Pensamiento del Lado Seco',
        body: 'Oil dissolves in oil — not in water. This is why you need solvents (dry-side agents) for oil stains. POG (Paint-Oil-Grease remover) is your first-line agent. It\'s a solvent that dissolves the oil so it can be flushed away. Think of it as "like dissolves like."',
        bodyEs: 'El aceite se disuelve en aceite — no en agua. Por eso necesitas solventes (agentes del lado seco) para manchas de aceite. POG es tu agente de primera línea. Es un solvente que disuelve el aceite para que pueda ser eliminado. Piensa en "lo similar disuelve lo similar."',
        visual: 'key-concept',
      },
      {
        heading: 'Treatment Approach',
        headingEs: 'Enfoque de Tratamiento',
        body: 'Apply POG directly to the stain. Allow dwell time (the solvent needs time to dissolve the oil). Tamp gently to work the solvent into the fabric. Flush with steam or dry cleaning solvent. For heavy grease: you may need multiple applications. For old set grease: the oil has oxidized and bonded — may need POG followed by a surfactant.',
        bodyEs: 'Aplica POG directamente en la mancha. Permite tiempo de acción (el solvente necesita tiempo para disolver el aceite). Tampona suavemente para trabajar el solvente en la tela. Enjuaga con vapor o solvente de limpieza en seco. Para grasa pesada: puede necesitar múltiples aplicaciones. Para grasa vieja fijada: el aceite se ha oxidado y unido — puede necesitar POG seguido de un surfactante.',
      },
    ],
    keyTakeaway: 'Oil needs solvents, not water. POG is your first-line agent. Like dissolves like.',
    keyTakeawayEs: 'El aceite necesita solventes, no agua. POG es tu agente de primera línea. Lo similar disuelve lo similar.',
  },
  {
    id: 'l6',
    title: 'Combination Stains',
    titleEs: 'Manchas de Combinación',
    icon: '🧩',
    objective: 'Learn the multi-step approach for stains that belong to multiple families.',
    objectiveEs: 'Aprende el enfoque de múltiples pasos para manchas que pertenecen a múltiples familias.',
    sections: [
      {
        heading: 'What Are Combination Stains?',
        headingEs: '¿Qué Son las Manchas de Combinación?',
        body: 'Many real-world stains don\'t fit neatly into one family. Lipstick = dye + oil + wax. Chocolate = protein (milk) + tannin (cocoa) + oil (cocoa butter). Gravy = protein + oil + tannin. Salad dressing = oil + tannin (vinegar). These require multi-step treatment in the right order.',
        bodyEs: 'Muchas manchas del mundo real no encajan en una sola familia. Labial = tinte + aceite + cera. Chocolate = proteína (leche) + tanino (cacao) + aceite (manteca de cacao). Salsa = proteína + aceite + tanino. Aderezo = aceite + tanino (vinagre). Estos requieren tratamiento de múltiples pasos en el orden correcto.',
        visual: 'key-concept',
      },
      {
        heading: 'The Order Rule',
        headingEs: 'La Regla del Orden',
        body: 'For combination stains, treat in this order:\n1. Oil/grease component FIRST (POG) — remove the oily layer\n2. Protein component SECOND (enzyme/protein formula) — break down proteins\n3. Tannin component THIRD (tannin formula) — break tannin bonds\n4. Dye component LAST (if any remains) — most aggressive treatment last\n\nWhy this order? Each agent works best when it can access the stain directly. Oil blocks water-based agents. Protein blocks tannin agents. Remove the layers in order.',
        bodyEs: 'Para manchas de combinación, trata en este orden:\n1. Componente de aceite/grasa PRIMERO (POG) — elimina la capa aceitosa\n2. Componente de proteína SEGUNDO (enzima/fórmula de proteína) — descompone proteínas\n3. Componente de tanino TERCERO (fórmula de tanino) — rompe enlaces de tanino\n4. Componente de tinte ÚLTIMO (si queda algo) — tratamiento más agresivo al final\n\n¿Por qué este orden? Cada agente funciona mejor cuando puede acceder a la mancha directamente. El aceite bloquea agentes a base de agua. La proteína bloquea agentes de tanino. Elimina las capas en orden.',
        visual: 'tip',
      },
      {
        heading: 'Real Scenario: Chocolate on a Silk Blouse',
        headingEs: 'Escenario Real: Chocolate en Blusa de Seda',
        body: 'Chocolate = cocoa butter (oil) + milk (protein) + cocoa (tannin). On silk — a high-risk fiber. Your approach:\n1. Test POG on hidden seam — check for dye bleed\n2. POG for the oil component — gentle, minimal pressure on silk\n3. Cold water flush\n4. Protein formula (test first — enzymes can damage silk)\n5. Tannin formula for remaining color\n6. Verify under light\n\nIf at any point the silk shows damage — STOP. Better to leave a faint shadow than destroy the fabric.',
        bodyEs: 'Chocolate = manteca de cacao (aceite) + leche (proteína) + cacao (tanino). En seda — una fibra de alto riesgo. Tu enfoque:\n1. Prueba POG en costura oculta — verifica sangrado de tinte\n2. POG para el componente de aceite — suave, mínima presión en seda\n3. Enjuague con agua fría\n4. Fórmula de proteína (prueba primero — las enzimas pueden dañar la seda)\n5. Fórmula de tanino para color restante\n6. Verificar bajo luz\n\nSi en cualquier punto la seda muestra daño — PARA. Es mejor dejar una sombra tenue que destruir la tela.',
        visual: 'scenario',
      },
    ],
    keyTakeaway: 'Combination stains require multi-step treatment in order: oil → protein → tannin → dye. Each layer must come off before the next agent can work.',
    keyTakeawayEs: 'Las manchas de combinación requieren tratamiento de múltiples pasos en orden: aceite → proteína → tanino → tinte. Cada capa debe salir antes de que el siguiente agente pueda funcionar.',
  },
  {
    id: 'l7',
    title: 'Oxidized & Set Stains',
    titleEs: 'Manchas Oxidadas y Fijadas',
    icon: '⏳',
    objective: 'Understand what happens chemically when a stain "sets" and how to approach old stains.',
    objectiveEs: 'Entender qué sucede químicamente cuando una mancha se "fija" y cómo abordar manchas viejas.',
    sections: [
      {
        heading: 'What Makes a Stain "Set"?',
        headingEs: '¿Qué Hace que una Mancha se "Fije"?',
        body: 'Three things set stains:\n1. Heat — denatures proteins, polymerizes tannins, bakes oil into fiber\n2. Time — oxidation changes the molecular structure\n3. Wrong treatment — soap on tannin, hot water on protein, the wrong agent at the wrong time\n\nA "set" stain has undergone a chemical change. The original molecule is gone — replaced by something harder to break down. This is why fresh stains are always easier than old ones.',
        bodyEs: 'Tres cosas fijan las manchas:\n1. Calor — desnaturaliza proteínas, polimeriza taninos, hornea aceite en la fibra\n2. Tiempo — la oxidación cambia la estructura molecular\n3. Tratamiento incorrecto — jabón en tanino, agua caliente en proteína, el agente incorrecto en el momento incorrecto\n\nUna mancha "fijada" ha sufrido un cambio químico. La molécula original se fue — reemplazada por algo más difícil de descomponer.',
        visual: 'key-concept',
      },
      {
        heading: 'Approaching Old Stains',
        headingEs: 'Abordando Manchas Viejas',
        body: 'For oxidized stains: you may need reducing agents (the opposite of oxidizers) to reverse the chemical change. For heat-set protein: usually permanent — manage expectations. For time-set tannin: extended dwell with tannin formula, possibly followed by careful bleaching. For old grease: POG with extended dwell, multiple applications, surfactant follow-up.',
        bodyEs: 'Para manchas oxidadas: puede necesitar agentes reductores (lo opuesto a los oxidantes) para revertir el cambio químico. Para proteína fijada por calor: generalmente permanente — maneja expectativas. Para tanino fijado por tiempo: acción prolongada con fórmula de tanino, posiblemente seguida de blanqueo cuidadoso. Para grasa vieja: POG con acción prolongada, múltiples aplicaciones, seguimiento con surfactante.',
      },
      {
        heading: 'The Honest Conversation',
        headingEs: 'La Conversación Honesta',
        body: 'Some set stains cannot be removed. Period. The best spotters know this and communicate it clearly: "This stain has set and I can reduce it, but it may not come out completely." This honesty builds more trust than false promises followed by a damaged garment.',
        bodyEs: 'Algunas manchas fijadas no se pueden eliminar. Punto. Los mejores spotters lo saben y lo comunican claramente: "Esta mancha se ha fijado y puedo reducirla, pero puede que no salga completamente." Esta honestidad construye más confianza que falsas promesas seguidas de una prenda dañada.',
        visual: 'tip',
      },
    ],
    keyTakeaway: 'Set stains have changed chemically. Heat, time, and wrong treatment are the three enemies. Some set stains are permanent — honesty is always better than damage.',
    keyTakeawayEs: 'Las manchas fijadas han cambiado químicamente. Calor, tiempo y tratamiento incorrecto son los tres enemigos. Algunas manchas fijadas son permanentes — la honestidad siempre es mejor que el daño.',
  },
]

export const MODULE_2_QUIZ: QuizQuestion[] = [
  {
    id: 'q1',
    type: 'multiple-choice',
    question: 'A customer brings in a shirt with a coffee stain from this morning. What stain family is this?',
    questionEs: 'Un cliente trae una camisa con una mancha de café de esta mañana. ¿A qué familia pertenece?',
    options: [
      { text: 'Protein', textEs: 'Proteína' },
      { text: 'Tannin', textEs: 'Tanino' },
      { text: 'Oil/Grease', textEs: 'Aceite/Grasa' },
      { text: 'Dye', textEs: 'Tinte' },
    ],
    correctIndex: 1,
    explanation: 'Coffee is a tannin stain — polyphenolic compounds from the coffee plant. Fresh tannin stains are relatively easy to treat with tannin formula.',
    explanationEs: 'El café es una mancha de tanino — compuestos polifenólicos de la planta de café. Las manchas frescas de tanino son relativamente fáciles de tratar con fórmula de tanino.',
    points: 10,
  },
  {
    id: 'q2',
    type: 'true-false',
    question: 'Hot water is the best first step for removing a blood stain.',
    questionEs: 'El agua caliente es el mejor primer paso para eliminar una mancha de sangre.',
    options: [
      { text: 'True', textEs: 'Verdadero' },
      { text: 'False', textEs: 'Falso' },
    ],
    correctIndex: 1,
    explanation: 'False. Blood is a protein stain. Heat denatures protein and sets it permanently — like cooking an egg. Always use COLD water on blood.',
    explanationEs: 'Falso. La sangre es una mancha de proteína. El calor desnaturaliza la proteína y la fija permanentemente — como cocinar un huevo. Siempre usa agua FRÍA en sangre.',
    points: 10,
  },
  {
    id: 'q3',
    type: 'multiple-choice',
    question: 'What is the correct treatment order for a chocolate stain (a combination stain)?',
    questionEs: '¿Cuál es el orden correcto de tratamiento para una mancha de chocolate (mancha de combinación)?',
    options: [
      { text: 'Tannin → Protein → Oil', textEs: 'Tanino → Proteína → Aceite' },
      { text: 'Protein → Oil → Tannin', textEs: 'Proteína → Aceite → Tanino' },
      { text: 'Oil → Protein → Tannin', textEs: 'Aceite → Proteína → Tanino' },
      { text: 'Oil → Tannin → Protein', textEs: 'Aceite → Tanino → Proteína' },
    ],
    correctIndex: 2,
    explanation: 'Oil first (POG), then protein (enzyme formula), then tannin (tannin formula). Each layer must come off before the next agent can access the stain beneath it.',
    explanationEs: 'Aceite primero (POG), luego proteína (fórmula de enzimas), luego tanino (fórmula de tanino). Cada capa debe salir antes de que el siguiente agente pueda acceder a la mancha debajo.',
    points: 10,
  },
  {
    id: 'q4',
    type: 'scenario',
    question: 'You\'re treating an ink stain on an expensive colored blazer. Your first test of the dye removal agent causes slight color change on the hidden seam. What do you do?',
    questionEs: 'Estás tratando una mancha de tinta en un blazer caro de color. Tu primera prueba del agente de remoción de tinte causa un ligero cambio de color en la costura oculta. ¿Qué haces?',
    options: [
      { text: 'Continue with a weaker solution', textEs: 'Continuar con una solución más débil' },
      { text: 'Try a different agent', textEs: 'Probar un agente diferente' },
      { text: 'Stop and return the garment with the stain', textEs: 'Parar y devolver la prenda con la mancha' },
      { text: 'Apply the agent quickly before it can affect the color', textEs: 'Aplicar el agente rápidamente antes de que afecte el color' },
    ],
    correctIndex: 2,
    explanation: 'Stop. The test showed the agent affects the garment\'s dye. A bleach spot or color change is worse than the original ink stain. Return the garment and explain honestly. This is professional judgment.',
    explanationEs: 'Para. La prueba mostró que el agente afecta el tinte de la prenda. Una mancha de blanqueador o cambio de color es peor que la mancha original de tinta. Devuelve la prenda y explica honestamente. Esto es juicio profesional.',
    points: 10,
  },
  {
    id: 'q5',
    type: 'multiple-choice',
    question: 'Why should you NOT apply soap or detergent to a fresh tannin stain before using tannin formula?',
    questionEs: '¿Por qué NO debes aplicar jabón o detergente a una mancha fresca de tanino antes de usar fórmula de tanino?',
    options: [
      { text: 'Soap is too alkaline', textEs: 'El jabón es demasiado alcalino' },
      { text: 'Soap creates soap-tannin complexes that set the stain', textEs: 'El jabón crea complejos jabón-tanino que fijan la mancha' },
      { text: 'Soap removes the tannin formula', textEs: 'El jabón elimina la fórmula de tanino' },
      { text: 'Soap is only for protein stains', textEs: 'El jabón es solo para manchas de proteína' },
    ],
    correctIndex: 1,
    explanation: 'Soap reacts with tannins to form soap-tannin complexes that bond more tightly to the fiber. This makes the stain harder to remove, not easier. Always use tannin formula first.',
    explanationEs: 'El jabón reacciona con los taninos para formar complejos jabón-tanino que se unen más fuertemente a la fibra. Esto hace la mancha más difícil de eliminar, no más fácil. Siempre usa fórmula de tanino primero.',
    points: 10,
  },
  {
    id: 'q6',
    type: 'multiple-choice',
    question: 'What is the first-line agent for an oil/grease stain?',
    questionEs: '¿Cuál es el agente de primera línea para una mancha de aceite/grasa?',
    options: [
      { text: 'Protein formula', textEs: 'Fórmula de proteína' },
      { text: 'Tannin formula', textEs: 'Fórmula de tanino' },
      { text: 'POG (Paint-Oil-Grease remover)', textEs: 'POG (removedor de Pintura-Aceite-Grasa)' },
      { text: 'Hydrogen peroxide', textEs: 'Peróxido de hidrógeno' },
    ],
    correctIndex: 2,
    explanation: 'POG is a solvent that dissolves oil — "like dissolves like." Water-based agents won\'t work on hydrophobic oil stains.',
    explanationEs: 'POG es un solvente que disuelve el aceite — "lo similar disuelve lo similar." Los agentes a base de agua no funcionan en manchas hidrofóbicas de aceite.',
    points: 10,
  },
]
